[package]
edition = "2021"
name = "day_20"
version = "0.1.0"

[[bench]]
harness = false
name = "button_press"

[profile.bench]
debug = true

[dev-dependencies]
criterion = "0.5.1"

[dependencies]
num = "0.4.1"
owo-colors = "4.0.0"
